In [2]:
import sys
sys.path.append("../src")

from preprocessing import (
    load_and_clean_data,
    prepare_features,
    create_preprocessor
)

df = load_and_clean_data(
    "../data/WA_Fn-UseC_-Telco-Customer-Churn.csv"
)

X, y = prepare_features(df)

preprocessor = create_preprocessor(X)

In [3]:
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier
)

In [4]:
lr_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    (
        "classifier",
        LogisticRegression(max_iter=1000)
    )
])

In [5]:
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    (
        "classifier",
        RandomForestClassifier(
            n_estimators=100,
            random_state=42
        )
    )
])

In [6]:
gb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    (
        "classifier",
        GradientBoostingClassifier(
            random_state=42
        )
    )
])

In [7]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [8]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [9]:
lr_cv_scores = cross_val_score(
    lr_pipeline,
    X,
    y,
    cv=cv,
    scoring="f1"
)

print("Scores:", lr_cv_scores)
print("Mean F1:", lr_cv_scores.mean())
print("Std:", lr_cv_scores.std())

Scores: [0.60869565 0.60115607 0.58381503 0.59097525 0.60882353]
Mean F1: 0.5986931069164574
Std: 0.009896110380880644

In [10]:
rf_cv_scores = cross_val_score(
    rf_pipeline,
    X,
    y,
    cv=cv,
    scoring="f1"
)

print("Scores:", rf_cv_scores)
print("Mean F1:", rf_cv_scores.mean())
print("Std:", rf_cv_scores.std())

Scores: [0.56621005 0.53395062 0.52552553 0.56580938 0.54938272]
Mean F1: 0.5481756568497289
Std: 0.01645007327604006

In [11]:
gb_cv_scores = cross_val_score(
    gb_pipeline,
    X,
    y,
    cv=cv,
    scoring="f1"
)

print("Scores:", gb_cv_scores)
print("Mean F1:", gb_cv_scores.mean())
print("Std:", gb_cv_scores.std())

Scores: [0.60208644 0.5794948  0.57393851 0.58630952 0.58947368]
Mean F1: 0.5862605904332577
Std: 0.009574899483739865

In [12]:
import pandas as pd

results_df = pd.read_csv(
    "../reports/model_results.csv"
)

results_df

                 Model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.796309   0.634675  0.548128  0.588235
1        Random Forest  0.787491   0.630662  0.483957  0.547655
2    Gradient Boosting  0.796731   0.642857  0.529412  0.580645

In [13]:
cv_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    
    "Mean CV F1": [
        lr_cv_scores.mean(),
        rf_cv_scores.mean(),
        gb_cv_scores.mean()
    ],

    "CV Std": [
        lr_cv_scores.std(),
        rf_cv_scores.std(),
        gb_cv_scores.std()
    ]
})

cv_results

                 Model  Mean CV F1    CV Std
0  Logistic Regression    0.598693  0.009896
1        Random Forest    0.548176  0.016450
2    Gradient Boosting    0.586261  0.009575

In [14]:
cv_results.to_csv(
    "../reports/cross_validation_results.csv",
    index=False
)

In [15]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [16]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [17]:
lr_cv_scores = cross_val_score(
    lr_pipeline,
    X,
    y,
    cv=cv,
    scoring="f1"
)

print("Scores:", lr_cv_scores)
print("Mean F1:", lr_cv_scores.mean())
print("Std:", lr_cv_scores.std())

Scores: [0.60869565 0.60115607 0.58381503 0.59097525 0.60882353]
Mean F1: 0.5986931069164574
Std: 0.009896110380880644

In [18]:
rf_cv_scores = cross_val_score(
    rf_pipeline,
    X,
    y,
    cv=cv,
    scoring="f1"
)

print("Scores:", rf_cv_scores)
print("Mean F1:", rf_cv_scores.mean())
print("Std:", rf_cv_scores.std())

Scores: [0.56621005 0.53395062 0.52552553 0.56580938 0.54938272]
Mean F1: 0.5481756568497289
Std: 0.01645007327604006

In [19]:
gb_cv_scores = cross_val_score(
    gb_pipeline,
    X,
    y,
    cv=cv,
    scoring="f1"
)

print("Scores:", gb_cv_scores)
print("Mean F1:", gb_cv_scores.mean())
print("Std:", gb_cv_scores.std())

Scores: [0.60208644 0.5794948  0.57393851 0.58630952 0.58947368]
Mean F1: 0.5862605904332577
Std: 0.009574899483739865

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [21]:
lr_pipeline.fit(X_train, y_train)
rf_pipeline.fit(X_train, y_train)
gb_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('classifier', GradientBoostingClassifier(random_state=42))])

In [22]:
lr_prob = lr_pipeline.predict_proba(X_test)[:, 1]
rf_prob = rf_pipeline.predict_proba(X_test)[:, 1]
gb_prob = gb_pipeline.predict_proba(X_test)[:, 1]

In [23]:
from sklearn.metrics import roc_auc_score

print(
    "Logistic ROC-AUC:",
    roc_auc_score(y_test, lr_prob)
)

print(
    "Random Forest ROC-AUC:",
    roc_auc_score(y_test, rf_prob)
)

print(
    "Gradient Boosting ROC-AUC:",
    roc_auc_score(y_test, gb_prob)
)

Logistic ROC-AUC: 0.8359290473207676
Random Forest ROC-AUC: 0.8136612120867004
Gradient Boosting ROC-AUC: 0.8386144918233069

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [25]:
lr_pipeline.fit(X_train, y_train)

rf_pipeline.fit(X_train, y_train)

gb_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('classifier', GradientBoostingClassifier(random_state=42))])

In [26]:
lr_prob = lr_pipeline.predict_proba(X_test)[:, 1]

rf_prob = rf_pipeline.predict_proba(X_test)[:, 1]

gb_prob = gb_pipeline.predict_proba(X_test)[:, 1]

In [27]:
from sklearn.metrics import roc_auc_score

In [28]:
lr_auc = roc_auc_score(
    y_test,
    lr_prob
)

rf_auc = roc_auc_score(
    y_test,
    rf_prob
)

gb_auc = roc_auc_score(
    y_test,
    gb_prob
)

In [29]:
print("Logistic Regression ROC-AUC:", lr_auc)
print("Random Forest ROC-AUC:", rf_auc)
print("Gradient Boosting ROC-AUC:", gb_auc)

Logistic Regression ROC-AUC: 0.8359290473207676
Random Forest ROC-AUC: 0.8136612120867004
Gradient Boosting ROC-AUC: 0.8386144918233069

In [30]:
auc_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "ROC-AUC": [
        lr_auc,
        rf_auc,
        gb_auc
    ]
})

auc_results

                 Model   ROC-AUC
0  Logistic Regression  0.835929
1        Random Forest  0.813661
2    Gradient Boosting  0.838614

In [31]:
auc_results.to_csv(
    "../reports/roc_auc_results.csv",
    index=False
)

In [32]:
from sklearn.metrics import roc_auc_score

print(
    "Logistic Regression:",
    roc_auc_score(y_test, lr_prob)
)

print(
    "Random Forest:",
    roc_auc_score(y_test, rf_prob)
)

print(
    "Gradient Boosting:",
    roc_auc_score(y_test, gb_prob)
)

Logistic Regression: 0.8359290473207676
Random Forest: 0.8136612120867004
Gradient Boosting: 0.8386144918233069

In [33]:
from sklearn.model_selection import GridSearchCV

lr_params = {
    "classifier__C": [
        0.01,
        0.1,
        1,
        10,
        100
    ],
    "classifier__class_weight": [
        None,
        "balanced"
    ]
}

In [34]:
lr_grid = GridSearchCV(
    estimator=lr_pipeline,
    param_grid=lr_params,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

lr_grid.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                                        ('cat',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('enco...
                                                                         Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                                       ('classifier',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid={'classifier__C': [0.01, 0.1, 1, 10, 100],
                         'classifier__class_weight': [None, 'balanced']},
             scoring='f1')

In [35]:
print(lr_grid.best_params_)
print(lr_grid.best_score_)

{'classifier__C': 1, 'classifier__class_weight': 'balanced'}
0.6333403588243568

In [36]:
best_lr = lr_grid.best_estimator_

In [37]:
gb_params = {
    "classifier__n_estimators": [
        50,
        100,
        200
    ],

    "classifier__learning_rate": [
        0.01,
        0.05,
        0.1
    ],

    "classifier__max_depth": [
        2,
        3,
        4
    ]
}

In [38]:
gb_grid = GridSearchCV(
    estimator=gb_pipeline,
    param_grid=gb_params,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

gb_grid.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                                        ('cat',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('enco...
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                                       ('classifier',
                                        GradientBoostingClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'classifier__learning_rate': [0.01, 0.05, 0.1],
                         'classifier__max_depth': [2, 3, 4],
                         'classifier__n_estimators': [50, 100, 200]},
             scoring='f1')

In [39]:
print(gb_grid.best_params_)
print(gb_grid.best_score_)

{'classifier__learning_rate': 0.1, 'classifier__max_depth': 4, 'classifier__n_estimators': 50}
0.5890954329639723

In [41]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

In [42]:
best_lr_prob = best_lr.predict_proba(X_test)[:, 1]

print(
    "LR Accuracy:",
    accuracy_score(y_test, best_lr_pred)
)

print(
    "LR Precision:",
    precision_score(y_test, best_lr_pred)
)

print(
    "LR Recall:",
    recall_score(y_test, best_lr_pred)
)

print(
    "LR F1:",
    f1_score(y_test, best_lr_pred)
)

print(
    "LR ROC-AUC:",
    roc_auc_score(y_test, best_lr_prob)
)

LR Accuracy: 0.7256574271499645
LR Precision: 0.4901315789473684
LR Recall: 0.7967914438502673
LR F1: 0.6069246435845214
LR ROC-AUC: 0.8351344145860403

In [43]:
import joblib

joblib.dump(
    best_lr,
    "../models/best_model.joblib"
)

['../models/best_model.joblib']